services:
  meetingsystem.api:
    image: ${DOCKER_REGISTRY-}meetingsystemapi
    build:
      context: .
      dockerfile: src/MeetingSystem.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionStrings__DefaultConnection=Server=meetingsystem.db,1433;Database=MeetingSystemDb;User Id=sa;Password=wfuZbFvsG3@2J#;TrustServerCertificate=True;
      - JWT_ISSUER=localhost
      - JWT_AUDIENCE=localhost
      - JWT_SECRET_KEY=GMAY*XAxuVv3Y5njS4JWJa$n4$EYd!iL$uTxat5hAJ&Ugf3By%tiWmHPKHpCr7f6
    ports:
      - "8080:8080"
      - "8081:8081" 
    depends_on:
      - meetingsystem.db

  meetingsystem.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meetingsystem_sql_server
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=wfuZbFvsG3@2J#
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data

volumes:
  mssql_data:

