services:
  meetingsystem.api:
    image: ${DOCKER_REGISTRY-}meetingsystemapi
    build:
      context: .
      dockerfile: src/MeetingSystem.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=meetingsystem.db,1433;Database=MeetingSystemDb;User Id=sa;Password=wfuZbFvsG3@2J#;TrustServerCertificate=True;
      - JWT_ISSUER=localhost
      - JWT_AUDIENCE=localhost
      - JWT_SECRET_KEY=GMAY*XAxuVv3Y5njS4JWJa$n4$EYd!iL$uTxat5hAJ&Ugf3By%tiWmHPKHpCr7f6
      - FILE_STORAGE_PATH=/app/uploads
    ports:
      - "8080:8080"
    depends_on:
       meetingsystem.db:
         condition: service_healthy
    volumes:
      - meetingsystem_uploads:/app/uploads

  meetingsystem.client:
    image: ${DOCKER_REGISTRY-}meetingsystemclient
    build:
      context: .
      dockerfile: src/MeetingSystem.Client/Dockerfile
    ports:
      - "3005:80"
    depends_on:
       meetingsystem.api:
        condition: service_started

  meetingsystem.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meetingsystem_sql_server
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=wfuZbFvsG3@2J#
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'wfuZbFvsG3@2J#' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  mssql_data:
  meetingsystem_uploads:

